---
# tasks file for elb
- name: create load balancer of AWS
  ec2_elb_lb:
     name: "{{lb}}"
     state: present
     aws_access_key: "{{ access_key }}"
     aws_secret_key: "{{ secret_key }}"
     region: "{{ region_name }}"
     cross_az_load_balancing: yes
     scheme: internet-facing
     security_group_names: "{{sg_name}}"
     listeners:
       - protocol: http
         load_balancer_port: 80
         instance_port: 81

- name: add instances to AWS ELB
     ec2_elb:
       #name: ec2lb
       aws_access_key: "{{access_key}}"
       aws_secret_key: "{{secret_key}}"
       instance_id: "{{item}}"
       ec2_elbs: "{{lb}}"
       state: present
       region: "{{region_name}}"
     loop: "{{instance_tag}}"
